# iron.yml
apiVersion: extensions/v1beta1 
kind: Deployment 
metadata:
  name: functions 
  labels:
    name: functions 
spec:
  replicas: 1 
  template:
    metadata:
      labels:
        name: functions 
    spec:
      containers:
      - name: functions
        image: iron/functions
        ports:
        - containerPort: 8080
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: sock
        - mountPath: /app/data
          name: data
      volumes:
        - name: sock
          hostPath: 
            path: /var/run/docker.sock
        - name: data
          hostPath: 
            path: /home/bean/work/src/functions/data
---
apiVersion: v1 
kind: Service
metadata:
  name: functions 
  labels:
    name: functions 
spec:
  ports:
    # the port that this service should serve on
    - port: 8080 
      targetPort: 8080 
  selector:
    name: functions 
